inherit_from:
  - rubocop.default.yml
  - rubocop-performance.default.yml
  - rubocop-rails.default.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  DisabledByDefault: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.7

#################### Layout ##############################

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

#################### Lint ################################

Lint/FlipFlop:
  Enabled: false

###################### Metrics ####################################

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*.rb'
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Max: 30

##################### Naming ##################################

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

##################### Performance #############################

# No overrides

##################### Rails ##################################

Rails/Delegate:
  Enabled: false

################## Security ##############################

# No overrides

################## Style #################################

Style/Alias:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Attr:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'
    member?: 'include?'

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  MinSize: 0
