# Hound: https://github.com/thoughtbot/hound/blob/master/config/style_guides/scss.yml
# SCSS-lint: https://github.com/causes/scss-lint/blob/master/config/default.yml

scss_files: "**/*.scss"

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false
  BorderZero:
    enabled: false
    convention: zero
  ColorKeyword:
    enabled: true
  ColorVariable:
    enabled: false # TODO: Pete should have a consistent color picking
  Comment:
    enabled: true
  DebugStatement:
    enabled: true
  DeclarationOrder:
    enabled: false # TODO: Automate it and re-enable it
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
    style: same_line
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true
  EmptyRule:
    enabled: true
  FinalNewline:
    enabled: true
    present: true
  HexLength:
    enabled: false
    style: short
  HexNotation:
    enabled: true
    style: lowercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: false # TODO: Replace IDs with classes and re-enable it
  ImportantRule:
    enabled: false # Need to override angular/bootstrap defaults
  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space
    width: 2
  LeadingZero:
    enabled: true
    style: include_zero
  MergeableSelector:
    enabled: true
    force_nesting: true
  NameFormat:
    enabled: false # TODO: remove active admin
    allow_leading_underscore: true
    convention: BEM
  NestingDepth:
    enabled: true
    max_depth: 10 # Uses a lower value when we have components and good CSS
  PlaceholderInExtend:
    enabled: false
  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 15 # default was 10
  PropertySortOrder:
    enabled: false # TODO: Automate-it and re-enable it
    ignore_unspecified: false
    separate_groups: false
  PropertySpelling:
    enabled: true
    extra_properties: []
  QualifyingElement:
    enabled: false # TODO: Convert to no-qualifying elements, re-enable it
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false
  SelectorDepth:
    enabled: false # TODO: When we have a nicer SCSS, enable-it
    max_depth: 2
  SelectorFormat:
    enabled: false # TODO: remove active admin
    convention: BEM
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space
  SpaceAfterPropertyName:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false
  SpaceBetweenParens:
    enabled: true
    spaces: 0
  StringQuotes:
    enabled: true
    style: double_quotes
  TrailingSemicolon:
    enabled: true
  TrailingZero:
    enabled: false
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    # Theorically awesome, why not? (and then we only have a few set of colors / fonts
    enabled: false
    properties: []
  VendorPrefixes:
    enabled: true
    identifier_list: bourbon
    include: []
    exclude: []
  ZeroUnit:
    enabled: true
  Compass::PropertyWithMixin:
    enabled: false

  # Allow underscores in names (because of Active Admin)
  NameFormat:
    enabled: false # Should use: convention: '^[a-z_-]+$'
